config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'static_pages#home'

  get 'users/food/:id' => 'users#food', as: 'users_food'

  get 'users/home/:id' => 'users#home', as: 'users_home'

  get 'foods/index' => 'foods#index', as:'food_lookup'

  get 'foods/:id/edit' => 'foods#edit', as:'food'

  get 'foods/:id/add' => 'foods#add', as:'add_food'

  get 'login' => 'sessions#new'

  post 'login' => 'sessions#create'

  get 'logout' => 'sessions#destroy'

  get 'signup' => 'users#new'

  resources :users
  resources :foods

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/food.rb
class Food < ApplicationRecord
	has_and_belongs_to_many :user	
end

app/models/user.rb
class User < ApplicationRecord
	has_secure_password
	has_and_belongs_to_many :foods
	validates :name, presence: true, length: {maximum: 50}
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, length: {maximum: 255}, 
		format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
	validates :current_weight, :target_weight,  numericality: { greater_than:0, less_than: 1000, allow_nil: true }
	validates :carb_percent, :protein_percent, :fat_percent,  numericality: { only_integer: true, greater_than: 0, less_than: 100, allow_nil: true }
	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  
  def new
    @food = Food.new
  end

  def create
  	@food = Food.new(food_params)
  	if @food.save!
  		render 'users/home'
  	else
  		render 'new'
  	end
  end

  def index
    @foods = Food.all
  end

  def edit
    @food = Food.find(params[:id])
    @food.save!
  end

  def add
    @food = Food.find(params[:id])
  end

end

private

def food_params
		params.require(:food).permit(:brand, :item, :serving_size, :servings, :calories, 
		:protein, :carbs, :sugars, :fiber, :fat) #separates parameters into aspects that are required (users) and permitted entries (avoiding any others for security purposes)
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to users_home_path
    else
    	redirect_to root_path
  	end

  end

  def destroy
  	log_out
  	redirect_to root_path
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

def home
end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
  	@user = User.new
  end

  def edit
  	@user = User.find(params[:id])
  	@user.save
  end

 def food
  	@user = User.find(params[:id])
  	# Determine user calorie target
    @user_rmr = (500 + (@user.current_weight/2.2) * (1- (@user.current_bodyfat/100)) * 22) 
  	if @user.activity_level = "Sedentary"
  		@user_rmr_and_activity = @user_rmr * 1.25
  	elsif @user.activity_level = "Lightly active"
  		@user_rmr_and_activity = @user_rmr * 1.55
  	elsif @user.activity_level = "Moderately active"
  		@user_rmr_and_activity = @user_rmr * 1.65
  	else
  		@user_rmr_and_activity = @user_rmr * 2
  	end

  	if @user.protein_percent > 30
  		@user_tef = @user_rmr * 0.15
  	else
  		@user_tef = @user_rmr * 0.1
  	end

  	if @user.desired_pace = "Lose 2 pounds a week"
  		@user_delta = -1000
  	elsif @user.desired_pace = "Lose 1 pound a week"
  		@user_delta = -500
  	elsif @user.desired_pace = "Maintain weight"
  		@user_delta = 0
  	elsif @user.desired_pace = "Gain 1 pound a week"
  		@user_delta = 500
  	else @user.desired_pace = "Gain 2 pounds a week"
  		@user_delta = 1000
  	end

  	@user.daily_calories = @user_rmr_and_activity + @user_tef + @user_delta

	@daily_calories = @user.daily_calories.round
	@user.save

  #Determine consumed calories

  @consumed_calories = 0

  #Determine burned calories

  @burned_calories = 0

  #Calculate remaining calories

  @remaining_calories = @daily_calories - @consumed_calories + @burned_calories

  @user.save

  #Calculate protein target

  @user.daily_protein = (@user.daily_calories * @user.protein_percent / 400).round
  @daily_protein = @user.daily_protein
  @user.save

  #Calculate protein consumed
  @consumed_protein = 0

  #Calculate protein remaining
  @remaining_protein = @daily_protein - @consumed_protein

  @user.save

  #Calculate carb target

  @user.daily_carbs = (@user.daily_calories * @user.carb_percent / 400).round
  @daily_carbs = @user.daily_carbs
  @user.save

  #Calculate carbs consumed
  @consumed_carbs = 0

  #Calculate carbs remaining
  @remaining_carbs = @daily_carbs - @consumed_carbs

  @user.save

  #Calculate fat target

  @user.daily_fat = (@user.daily_calories * @user.fat_percent / 900).round
  @daily_fat = @user.daily_fat
  @user.save

  #Calculate fat consumed
  @consumed_fat = 0

  #Calculate fat remaining
  @remaining_fat = @daily_fat - @consumed_fat

  @user.save

  end

  def create
  	@user = User.new(user_params)
  	if @user.save
  		redirect_to users_goals_path(@user)
  	else
  		redirect_to 'new'
  	end
  end

  def update
  	@user = User.find(params[:id])
  	if @user.update_attributes(user_params)
  		render 'home'
  	else
  		render 'goals'
  	end
  end

  def home
    @user = User.find(params[:id])
    @username = @user.name
  end
 
 end


private

def user_params
		params.require(:user).permit(:name, :email, :password, :password_confirmation, :target_weight, 
		:current_weight, :desired_pace, :current_bodyfat, :activity_level, :carb_percent, :protein_percent, :fat_percent) #separates parameters into aspects that are required (users) and permitted entries (avoiding any others for security purposes)

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def log_in(user)
		session[:user_id] = user.id
	end

	def current_user
		@current_user ||= User.find_by(id: session[:user_id])
	end

	def logged_in?
		!current_user.nil?
	end

	def log_out
		session.delete(:user_id)
		@current_user = nil
	end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

end

app/views/foods/add.html.erb
<h1>Add Food</h1>

<div class = "row">
	<div class = "col-md-6 col-md-offset-3">
		<%= form_for(@food) do |f| %>

		<%= f.label :brand %>
		<%= f.text_field :brand, class: 'form-control' %>

		<%= f.label :item %>
		<%= f.text_field :item, class: 'form-control' %>

		<%= f.label :serving_size %>
		<%= f.text_field :serving_size, class: 'form-control' %>

		<%= f.label '# of servings' %>
		<%= f.number_field :servings, class: 'form-control' %>

		<%= f.label :calories %>
		<%= f.number_field :calories, class: 'form-control' %>

		<%= f.label 'Protein (g)' %>
		<%= f.number_field :protein, class: 'form-control' %>

		<%= f.label 'Carbs (g)' %>
		<%= f.number_field :carbs, class: 'form-control' %>

		<%= f.label 'Sugars (g)' %>
		<%= f.number_field :sugars, class: 'form-control' %>

		<%= f.label 'Fiber (g)' %>
		<%= f.number_field :fiber, class: 'form-control' %>

		<%= f.label 'Fat (g)' %>
		<%= f.number_field :fat, class: 'form-control' %>		

		<%= f.submit "Add food", class: "btn btn-primary"  %>
		<% end %>
	</div>
</div>

app/views/foods/edit.html.erb
<h1>Edit Food</h1>

<div class = "row">
	<div class = "col-md-6 col-md-offset-3">
		<%= form_for(@food) do |f| %>

		<%= f.label :brand %>
		<%= f.text_field :brand, class: 'form-control' %>

		<%= f.label :item %>
		<%= f.text_field :item, class: 'form-control' %>

		<%= f.label :serving_size %>
		<%= f.text_field :serving_size, class: 'form-control' %>

		<%= f.label '# of servings' %>
		<%= f.number_field :servings, class: 'form-control' %>

		<%= f.label :calories %>
		<%= f.number_field :calories, class: 'form-control' %>

		<%= f.label 'Protein (g)' %>
		<%= f.number_field :protein, class: 'form-control' %>

		<%= f.label 'Carbs (g)' %>
		<%= f.number_field :carbs, class: 'form-control' %>

		<%= f.label 'Sugars (g)' %>
		<%= f.number_field :sugars, class: 'form-control' %>

		<%= f.label 'Fiber (g)' %>
		<%= f.number_field :fiber, class: 'form-control' %>

		<%= f.label 'Fat (g)' %>
		<%= f.number_field :fat, class: 'form-control' %>		

		<%= f.submit "Change food", class: "btn btn-primary"  %>
		<% end %>
	</div>
</div>

app/views/foods/index.html.erb
<h1>Food Lookup</h1>

<div class = "table-hover">
	<table class = "table">
	  <thead>
	    <tr>
	      <th>Brand</th>
	      <th>Item</th>
	      <th>Serving Size</th>
	      <th>Calories</th>
	      <th>Protein</th>
	      <th>Carbs</th>
	      <th>Sugars</th>
	      <th>Fiber</th>
	      <th>Fat</th>
	      <th colspan="3"></th>
	    </tr>
	  </thead>

	  <tbody>
	    <% @foods.each do |food| %>
	      <tr>
	        <td><%= food.brand %></td>
	        <td><%= food.item %></td>
	        <td><%= food.serving_size %></td>
	        <td><%= food.calories %></td>
	        <td><%= food.protein %></td>
	        <td><%= food.carbs %></td>
	        <td><%= food.sugars %></td>
	        <td><%= food.fiber %></td>
	        <td><%= food.fat %></td>
	        <td><%= link_to 'Add', add_food_path(food.id) %></td>
	        <td><%= link_to 'Edit', edit_food_path(food.id) %></td>
	        <td><%= link_to 'Destroy', food, method: :delete, data: { confirm: 'Are you sure?' } %></td>
	      </tr>
	    <% end %>
	  </tbody>
	</table>
</div>

<br>

<%= link_to 'Add New Food', new_food_path, :class => "btn btn-default", id: "add_food_button" %>

app/views/foods/new.html.erb
<h1>Add New Food</h1>

<div class = "row">
	<div class = "col-md-6 col-md-offset-3">
		<%= form_for(@food) do |f| %>

		<%= f.label :brand %>
		<%= f.text_field :brand, class: 'form-control' %>

		<%= f.label :item %>
		<%= f.text_field :item, class: 'form-control' %>

		<%= f.label :serving_size %>
		<%= f.text_field :serving_size, class: 'form-control' %>

		<%= f.label '# of servings' %>
		<%= f.number_field :servings, class: 'form-control' %>

		<%= f.label :calories %>
		<%= f.number_field :calories, class: 'form-control' %>

		<%= f.label 'Protein (g)' %>
		<%= f.number_field :protein, class: 'form-control' %>

		<%= f.label 'Carbs (g)' %>
		<%= f.number_field :carbs, class: 'form-control' %>

		<%= f.label 'Sugars (g)' %>
		<%= f.number_field :sugars, class: 'form-control' %>

		<%= f.label 'Fiber (g)' %>
		<%= f.number_field :fiber, class: 'form-control' %>

		<%= f.label 'Fat (g)' %>
		<%= f.number_field :fat, class: 'form-control' %>		

		<%= f.submit "Add food", class: "btn btn-primary"  %>
		<% end %>
	</div>
</div>

app/views/layouts/_header.html.erb
<header class = "navbar navbar-fixed-top navbar-inverse">
	<div class ="container">
		<% if logged_in? %>
			<%= link_to "Build", users_home_path(@current_user), id: "logo" %>
		<% else  %>
		<% end %>
		<nav>
			<ul class = "nav navbar-nav navbar-right">
				<% if logged_in? %>
					<li><%= link_to "Food", users_food_path(@current_user) %></li>
					<li><%= link_to "Goals", edit_user_path(@current_user) %></li>
					<li><%= link_to "Log Out", logout_path %></li>
				<% else  %>
				<% end %>		
			</ul>
		</nav>
	</div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FitnessApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
	<%= render 'layouts/header' %>
		 
	  <%= yield %>
		
  </body>

</html>

app/views/static_pages/food.html.erb
<h1>Food Dashboard</h1>

<h3>Calories</h3>
<p> Target:</p>
<p> Consumed:</p>
<p> Remaining:</p>

<h3>Protein</h3>
<p> Target:</p>
<p> Consumed:</p>
<p> Remaining:</p>

<h3>Carbs</h3>
<p> Target:</p>
<p> Consumed:</p>
<p> Remaining:</p>

app/views/static_pages/home.html.erb
<div class = "home_page">

	<h1>Build</h1>

	<h3>“You cannot dream yourself into a character: you must hammer and forge yourself into one.”</h3>
	
	<img src= 'http://798ba1b174f0e6a04a8efe01.thevladarcompany.netdna-cdn.com/wp-content/uploads/2014/06/Pumping-Iron-8-1560x690_c.jpg'>

	<%= link_to "Sign Up", signup_path, :class => "btn btn-default", id: "home_buttons" %>
	<%= link_to "Log In", login_path, :class => "btn btn-default", id: "home_buttons" %>

</div>

app/views/users/edit.html.erb
<h1>Set Your Goals</h1>

<div class = "row">
	<div class = "col-md-6 col-md-offset-3">
		<%= form_for(@user) do |f| %>

		<%= f.label :target_weight %>
		<%= f.number_field :target_weight, class: 'form-control' %>

		<%= f.label :current_weight %>
		<%= f.number_field :current_weight, class: 'form-control' %>

		<%= f.label :desired_pace %>
		<%= f.select :desired_pace, ["Lose 2 pounds a week", "Lose 1 pound a week", "Maintain weight", "Gain 1 pound a week", "Gain 2 pounds a week"], class: 'form-control' %>

		<%= f.label 'Current bodyfat %' %>
		<%= f.number_field :current_bodyfat, class: 'form-control' %>

		<%= f.label :activity_level %>
		<%= f.select :activity_level, ["Sedentary", "Lightly active", "Moderately active", "Very active"], class: 'form-control' %>

		<%= f.label 'Desired % of calories from carbs' %>
		<%= f.select :carb_percent, (0..20).to_a.map{|n| [n * 5]}, class: 'form-control' %>

		<%= f.label 'Desired % of calories from protein' %>
		<%= f.select :protein_percent, (0..20).to_a.map{|n| [n * 5]}, class: 'form-control' %>		

		<%= f.label 'Desired % of calories from fat' %>
		<%= f.select :fat_percent, (0..20).to_a.map{|n| [n * 5]}, class: 'form-control' %>		

		<%= f.submit "Let's get started", class: "btn btn-primary"  %>
		<% end %>
	</div>
</div>

app/views/users/food.html.erb
<h1>Calorie and Macro Dashboard</h1>

<div class = "row">
	<div class = "col-md-3">
		<div class = "well">
			<h3>Calories</h3>
			<p> Net target: <%= @daily_calories %></p>
			<p> Consumed: <%= @consumed_calories %></p>
			<p> Burned: <%= @burned_calories %></p>
			<p> Remaining: <%= @remaining_calories %> </p>
		</div>
	</div>
	<div class = "col-md-3">
		<div class = "well">
			<h3>Protein (g)</h3>
			<p> Target: <%= @daily_protein %> </p>
			<p> Consumed: <%= @consumed_protein %></p>
			<p> Remaining: <%= @remaining_protein %></p>
		</div>
	</div>
	<div class = "col-md-3">
		<div class = "well">
			<h3>Carbs (g)</h3>
			<p> Target: <%= @daily_carbs %></p>
			<p> Consumed: <%= @consumed_carbs %></p>
			<p> Remaining: <%= @remaining_carbs %></p>
		</div>
	</div>
	<div class = "col-md-3">
		<div class = "well">
			<h3>Fat (g)</h3>
			<p> Target: <%= @daily_fat %></p>
			<p> Consumed: <%= @consumed_fat %></p>
			<p> Remaining: <%= @remaining_fat %></p>
		</div>
	</div>

app/views/users/goals.html.erb
<h1>Set Your Goals</h1>

<div class = "row">
	<div class = "col-md-6 col-md-offset-3">
		<%= form_for(@user) do |f| %>

		<%= f.label :target_weight %>
		<%= f.number_field :target_weight, class: 'form-control' %>

		<%= f.label :current_weight %>
		<%= f.number_field :current_weight, class: 'form-control' %>

		<%= f.label :desired_pace %>
		<%= f.select :desired_pace, ["Lose 2 pounds a week", "Lose 1 pound a week", "Maintain weight", "Gain 1 pound a week", "Gain 2 pounds a week"], class: 'form-control' %>

		<%= f.label 'Current bodyfat %' %>
		<%= f.number_field :current_bodyfat, class: 'form-control' %>

		<%= f.label :activity_level %>
		<%= f.select :activity_level, ["Sedentary", "Lightly active", "Moderately active", "Very active"], class: 'form-control' %>

		<%= f.label 'Desired % of calories from carbs' %>
		<%= f.select :carb_percent, (0..20).to_a.map{|n| [n * 5]}, class: 'form-control' %>

		<%= f.label 'Desired % of calories from protein' %>
		<%= f.select :protein_percent, (0..20).to_a.map{|n| [n * 5]}, class: 'form-control' %>		

		<%= f.label 'Desired % of calories from fat' %>
		<%= f.select :fat_percent, (0..20).to_a.map{|n| [n * 5]}, class: 'form-control' %>		

		<%= f.submit "Let's get started", class: "btn btn-primary"  %>
		<% end %>
	</div>
</div>

app/views/users/home.html.erb
<h1>Welcome, <%= @username %>!<h1>

<div class ="btn-group">
	<%= link_to "Quick Add: Food", food_lookup_path, :class => "btn btn-default", id: "add_buttons" %>
	<%= link_to "Quick Add: Water", '#', :class => "btn btn-default", id: "add_buttons" %>
	<%= link_to "Quick Add: Sleep", '#', :class => "btn btn-default", id: "add_buttons" %>
	<%= link_to "Quick Add: Workout", '#', :class => "btn btn-default", id: "add_buttons" %>
</div>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<div class = "row">
	<div class = "col-md-6 col-md-offset-3">
		<%= form_for(@user) do |f| %>

		<%= f.label :name %>
		<%= f.text_field :name, class: 'form-control' %>

		<%= f.label :email %>
		<%= f.email_field :email, class: 'form-control' %>

		<%= f.label :password %>
		<%= f.password_field :password, class: 'form-control' %>

		<%= f.label :password_confirmation, "Confirmation" %>
		<%= f.password_field :password_confirmation, class: 'form-control' %>

		<%= f.submit "Create my account", class: "btn btn-primary"  %>
		<% end %>
	</div>
</div>

app/views/users/show.html.erb
<h1>Welcome!<h1>

<%= button_to'Quick Add: Food', '#' %>
<%= button_to 'Quick Add: Water', '#' %>
<%= button_to 'Quick Add: Sleep', '#' %>
<%= button_to 'Quick Add: Workout', '#' %>

app/views/users/user_home.html.erb
<h1>Welcome!<h1>

<%= button_to'Quick Add: Food', '#' %>
<%= button_to 'Quick Add: Water', '#' %>
<%= button_to 'Quick Add: Sleep', '#' %>
<%= button_to 'Quick Add: Workout', '#' %>